model:
  initialize_from: outputs/lausanne_0_coarse/checkpoints/epoch=29-step=30000.ckpt
  overwrite_config: False
  gaussian:
    init_args:
      sh_degree: 2
      optimization:
        means_lr_init: 1.6e-4
        means_lr_scheduler:
          lr_final: 1.6e-6
          max_steps: 30_000
        scales_lr: 0.001
  renderer:
    class_path: internal.renderers.vanilla_trim_renderer.VanillaTrimRenderer
    init_args:
      prune_ratio: 0.8
      diable_trimming: true
  
  metric:
    class_path: internal.metrics.citygsv2_metrics.CityGSV2Metrics
    init_args:
      lambda_normal: 0.0125
      normal_regularization_from_iter: 0
      depth_loss_type: l1+ssim
      depth_loss_ssim_weight: 1.0
      depth_loss_weight:
        init: 0.5
        final_factor: 0.05

trainer:
  check_val_every_n_epoch: 20
  max_steps: 20000

data:
  path: data/lausanne/dense_middle/0
  parser:
    class_path: EstimatedDepthBlockColmap
    init_args:
      down_sample_factor: 4
      depth_scale_lower_bound: 0.01
      depth_scale_upper_bound: 50.0
      content_threshold: 0.05
      block_dim:  # removed z dimension
      - 4
      - 4

save_iterations:
- 1000
- 5000
- 10000
- 20000
- 30000